### PR TITLE
Check heap size before running example

### PR DESCRIPTION
**Pull request by c1728p9**
Before starting the example, first check that there is enough heap space to succeed. If there is not enough then print an error message and exit rather than attempting run then example and failing.

This makes failures like in #16 more obvious since the example quits before any encryption is performed.

### CODE REVIEW

**Comment by c1728p9** [comment]
Heap usage on the K64F with the current configuration is ~55296 bytes.

**Comment by kjbracey-arm** [comment]
Maybe a warning and proceeding, rather than refusal to even attempt? We do sometimes try to squeeze into really small platforms, squeezing config, and an refusal based on an overestimate based on a larger config would be really annoying.

**Comment by c1728p9** [comment]
Good idea. I update the PR so it prints a warning and continues.

**Comment by sbutcher-arm** [comment]
My concern with this PR is that you're using a static estimate for heap, and yet the heap usage can vary a lot depending on what the mbed TLS configurations used are. This check only seems valid with the default configuration that we intend for mbed OS, but the actual configuration can change from board to board as well as be influenced by the user.

Even if we try to choose a safe maximum it's hard, and will likely be a figure much higher than the estimate you have here - if someone decides to add back in all the options we've removed to save space.

So I don't see how we can meaningfully introduce this check.

I think it may be a better idea to add this sample to the test suite of tests executed on each mbed board in our CI system.

**Comment by c1728p9** [comment]
Hi @sbutcher-arm, this is just a warning if the example is likely to fail. It will try to run the example anyway. How much would you expect heap usage to change from board to board? The only thing I know of that the board is able to change is if a TRNG or NV seed is present.

Another possibility is to have mbedtls_ssl_handshake() return a status which indicates that it ran out of memory. That would be a more general solution, but as TLS was just updated it might be a while before a version like this can be released.

**Comment by sbutcher-arm** [comment]
@c1728p9 

> How much would you expect heap usage to change from board to board?

Our weekly test figures go from ~6kb up to 32kb. The target can and will change the configurations if it wants to, as well as application software so there's no standard baseline we can depend on. For the sample, we may be able to rule out other application software, but we can't rule our changes from the target.

I think your suggestion of better handling of OOM conditions is much more sensible, and the way to go. That is probably what it should be doing already.

**Comment by c1728p9** [comment]
I created https://github.com/ARMmbed/mbedtls/issues/663 to track this change in TLS.

**Comment by sbutcher-arm** [comment]
Closing this PR has we will resolve this by another means as discussed.

**Pull request closed without merging**
